### ISSUE TITLE
GTmetrix : Page size should be 2MB and below

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Greenstar-Mechanical-Services#28]
https://gtmetrix.com/reports/greenstar-imp.stage.titanweb.com.au/tQCRMbAx
![2016-05-04_1403](https://cloud.githubusercontent.com/assets/13309730/15009626/0c2516be-1205-11e6-8f2b-21eed63aa193.png)

**Comment by suniltitan** [comment]
http://greenstar-imp.stage.titanweb.com.au/wp-content/themes/titan/fonts/Lato-Semibold.woff - 554.7 kB
http://greenstar-imp.stage.titanweb.com.au/wp-content/themes/titan/fonts/Lato-Heavy.woff - 557.6 kB
http://greenstar-imp.stage.titanweb.com.au/wp-content/themes/titan/fonts/Lato-MediumItalic.woff - 588.2 kB
http://greenstar-imp.stage.titanweb.com.au/wp-content/themes/titan/fonts/Lato-Medium.woff - 546.3 kB
http://greenstar-imp.stage.titanweb.com.au/wp-content/themes/titan/fonts/Lato-Black.woff - 524.3 kB

  -----> Above font files add more than 2.7 MB to total file size
