### ISSUE TITLE
Home-Banner(Click here to contact us today) : Unable to click enter the name in Your name on devices field

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Greenstar-Mechanical-Services#36]
Devices : Ipad, Ipad(mini), Samsung E7, Itouch
![2016-05-04_1434](https://cloud.githubusercontent.com/assets/13309730/15012405/03bec50e-1216-11e6-8f3c-2af95deb4fdb.png)

**Comment by roseliesromeo** [comment]
Form should entirely be displayed below the banner image.

**Comment by roseliesromeo** [comment]
Not fixed in 769-991 resolution
![image](https://cloud.githubusercontent.com/assets/11186313/15201839/a32c8524-1827-11e6-9b4e-29a251d1c008.png)
