### ISSUE TITLE
Banner : Banner title is not displaying on devices

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Greenstar-Mechanical-Services#39]
Devices : Ipad, Ipad(mini), Samsung E7
![2016-05-04_1641](https://cloud.githubusercontent.com/assets/13309730/15012573/5a06bf88-1217-11e6-8b67-27017d02567c.png)

**Comment by roseliesromeo** [comment]
Not fixed.  Banner text isn't displayed for 991 resolution and below.
![image](https://cloud.githubusercontent.com/assets/11186313/15136939/a9a3d1ca-16b8-11e6-96e7-43964b3d691a.png)
