### ISSUE TITLE
Service & Maintenance page : Alignment is not implemented properly on devices 

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Greenstar-Mechanical-Services#42]
Devices : Ipad, Ipad(mini), Samsung E7, Itouch
![2016-04-26_1653](https://cloud.githubusercontent.com/assets/13309730/15012899/d5c7a216-1219-11e6-8fc5-4111cb6332a4.png)

**Comment by roseliesromeo** [comment]
Not fixed when re-sized to the mentioned resolutions.
![image](https://cloud.githubusercontent.com/assets/11186313/15135002/1393b2e0-16a4-11e6-98e1-c7c96f84f7f9.png)
