### ISSUE TITLE
Admin : Client login and employee login fields are overlapping with logo when facebook and linkdin social icons are removed

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Greenstar-Mechanical-Services#7]
![2016-04-25_1647](https://cloud.githubusercontent.com/assets/13309730/14782262/d9c387d8-0b05-11e6-8167-77b4eb8a7ab2.png)

**Comment by mahender-sowedane** [comment]
Still issue is not fixed.
![2016-05-03_1427](https://cloud.githubusercontent.com/assets/13309730/14978710/73d42c34-113b-11e6-81d0-465570074d6b.png)

**Comment by roseliesromeo** [comment]
If there is no social icons, the Login buttons overlap with the header logo.
![image](https://cloud.githubusercontent.com/assets/11186313/15136491/a441fb20-16b4-11e6-8083-83b1b8c47f21.png)
